### ISSUE TITLE
Куча ошибок.

### ISSUE THREAD

**Issue by korenevskiy** [modulbank-pay/modulbank-joomshopping#1]
Что это за муть ?
Установил плагин скаченный по ссылке указанный в нотации(описании) в инструкции тут [//github.com/modulbank-pay/modulbank-joomshopping](url) Установка прошла успешно.
Потом захожу в платежные модули магазина.
и вижу это
https://yadi.sk/i/ETzGFuiKBkmNAg
и это
https://yadi.sk/i/RB_J0dcKBSCmCQ
-------------------
### Версия:
PHP 7.1.26
Joomla! 3.9.2	
JoomShopping 4.18.2

**Comment by VampiRUS** [comment]
Поправил
