### ISSUE TITLE
Функция checkTransaction в процессе оплаты не вызывается, статус заказа не меняется

### ISSUE THREAD

**Issue by barancev** [modulbank-pay/modulbank-joomshopping#3]
Функция checkTransaction в процессе оплаты не вызывается, от сервера не приходит колбек с параметрами controller=checkout&task=step7&act=notify, поэтому даже после оплаты заказ остаётся в статусе Pending

**Comment by VampiRUS** [comment]
Нужно в логах вебсервера смотреть, если ли запрос в логах и не блокируется ли он хостером.
По этому вопросу нужно в тех.поддержку обращаться. Там помогут.

**Comment by barancev** [comment]
Хостер совершенно точно ничего не блокирует. Проверено на двух разных магазинах, находящихся у двух разных хостеров. Кроме того, другие платёжные системы (например, pm_paymaster) благополучно присылают команду notify и смена статуса отрабатывает.

Такой коллбек вообще запроектирован? Честно говоря, я даже не могу найти, где он настраивается. В конфигурации плагина есть настройка "Адрес для перехода после успешной оплаты", но там используется команда return, а не notify, при выполнении этой команды просто показывается финальное сообщение о том, что "оплата получена", смены статуса заказа не происходит. Других подходящих настроек обнаружить не удалось.

**Comment by VampiRUS** [comment]
Проверьте, есть ли в логах вебсервера запросы на index.php?option=com_jshopping&controller=checkout&task=step7&act=notify&js_paymentclass=pm_modulbank&no_lang=1&order_id=
Если нет, то нужно обратиться в ТП модульбанка.

**Comment by barancev** [comment]
Сначала хотелось бы понять, как модульбанк догадывается о том, что нужно отправить запрос на этот адрес? Где именно в настройках плагина он указывается? Какой параметр запроса, отправляемого в модульбанк, отвечает за этот коллбек?

Есть открытое описание API модульбанка или его нужно запрашивать у техподдержки?

**Comment by VampiRUS** [comment]
Её нигде указывать не нужно её передаёт модуль
https://moduldev.atlassian.net/wiki/spaces/IE/pages/12288021/API+1.2
